### ISSUE TITLE
Simplify default circleci config file

### ISSUE THREAD

**Issue by pixelastic** [pixelastic/aberlaas#127]
All the caching logic seems to be abstracted by using the `node` orb like this:

```
version: 2.1

orbs:
  node: circleci/node@4.5.1

jobs:
  ci:
    docker:
      - image: cimg/node:14.17.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: 'yarn'
      - add_ssh_keys
      - run: 'yarn run ci'

workflows:
  version: 2
  # On every commit
  commit:
    jobs:
      - ci
```

Currently in use in `firost` and `gods`
